#!/usr/bin/env python
import sys
import clientnode
import masternode

if __name__ == '__main__':

    port = None
    if len(sys.argv) < 3:
        print("Missing parameters")
        sys.exit(1)
    if len(sys.argv) == 4:
        port = sys.argv[3]

    module = sys.argv[1]
    command = sys.argv[2]
    if module == "masternode" and command == "start":

        if port is None:
            masternode.start()
        else:
            masternode.start(port)

    elif module == "clientnode" and command == "start":
        try:
            ip_address = sys.argv[3]

            if len(sys.argv) == 5:
                port = sys.argv[4]
                clientnode.start(ip_address, port)
            elif len(sys.argv) == 6:
                port = sys.argv[4]
                client_id = sys.argv[5]
                clientnode.start(ip_address, port, client_id)
            else:
                clientnode.start(ip_address)

        except IndexError:
            print("Missing parameters. ")

    else:
        print("Error parameters. See to documentation.")

